### ISSUE TITLE
KeyError: 'blur_radius'

### ISSUE THREAD

**Issue by robotzheng** [fancompute/wavetorch#7]
python3 ./study/vowel_train.py ./study/example.yml
Configuration: ./study/example.yml
Dataset: 12 vowel samples
Traceback (most recent call last):
  File "./study/vowel_train.py", line 110, in <module>
    blur_radius=cfg['geom']['blur_radius'],
KeyError: 'blur_radius'

**Comment by ianwilliamson** [comment]
Fixed in 927ad02dc9db83f72b8df1d91418a6681e60fd56.
